Oz/s1186 plugin fixes
blinkops/blink-jira pull request #4
Opened 2021-12-05 16:09 UTC by ozhey

added custom actions

2021-12-05 16:16 UTC, shirleygordon-blink commented on custom_actions/actions/RemoveUser.action.yaml
> +    description: " The email of the user, which uniquely identifies the user across all Atlassian products."
you have an unnecessary whitespace here :)

2021-12-05 16:19 UTC, shirleygordon-blink requested changes
the readme file should be updated as well, some param descriptions should be fixed, for instance AddComment's expand param: "Use [expand](#expansion) to include..."
also the links in the readme aren't formatted properly

2021-12-06 08:54 UTC, ozhey commented on custom_actions/actions/RemoveUser.action.yaml
> +    description: " The email of the user, which uniquely identifies the user across all Atlassian products."
hawkeye

2021-12-06 10:28 UTC, YakirOren commented on custom_actions/actions/RemoveUser.action.yaml
> +    description: " The email of the user, which uniquely identifies the user across all Atlassian products."
`yq e -i custom_actions/actions/RemoveUser.action.yaml`

2021-12-06 11:00 UTC, ozhey commented
> the readme file should be updated as well, some param descriptions should be fixed, for instance AddComment's expand param: "Use [expand](#expansion) to include..." also the links in the readme aren't formatted properly

done

2021-12-06 14:32 UTC, shirleygordon-blink approved these changes
great job :)

2021-12-06 14:33 UTC, merged